misc:
  hide_status_window: false
  noise_on_completion: false
  pitch_detection_enabled: true
  pitch_target: 96.96969696969697
  pitch_unwanted: 108.10810810810811
  print_to_terminal: true
model_options:
  api:
    api_key: null
    base_url: https://api.openai.com/v1
    model: gpt-4o-transcribe
  common:
    initial_prompt: "Clean transcription without filler words. Swedish, English, and Swinglish mixed. Artcraft, Autodoro, Headon, Intender, Jhana, NixOS, WhisperWriter. pusha, mergea, Claude Code."
    language: null
    temperature: 0.0
  local:
    compute_type: float16
    condition_on_previous_text: true
    device: cuda
    hotwords: []
    model: small
    model_path: null
    vad_filter: false
  use_api: true
post_processing:
  add_trailing_space: true
  input_method: xdotool
  remove_capitalization: false
  remove_trailing_period: false
  replace_slash_word: true
  writing_key_press_delay: 0.005
recording_options:
  activation_key: ctrl_right
  input_backend: pynput
  min_duration: 100
  recording_mode: hold_to_record
  sample_rate: 16000
  silence_duration: 900
  sound_device: null
